Repository tjsduq0423/WhereIsMyHome, pull requests merged in 2023-05, with the labels that each got.

#20 19 질의 응답 게시판 UI
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/assets/data/QnAData.js
  FrontEnd/src/assets/data/noticeData.js
  FrontEnd/src/assets/img/Qna01.jpg
  FrontEnd/src/components/AppBoardForm.vue
  FrontEnd/src/components/AppCardHeader.vue
  FrontEnd/src/components/AppContent.vue
  FrontEnd/src/components/AppFooter.vue
  FrontEnd/src/components/AppNav.vue
  FrontEnd/src/components/AppPaginationBar.vue
  FrontEnd/src/router/index.js
  FrontEnd/src/views/auth/LoginView.vue
  FrontEnd/src/views/board/NoticeCreateView.vue
  FrontEnd/src/views/board/NoticeDetailView.vue
  FrontEnd/src/views/board/NoticeEditView.vue
  FrontEnd/src/views/board/NoticeView.vue
  FrontEnd/src/views/board/QnACreateView.vue
  FrontEnd/src/views/board/QnADetailView.vue
  FrontEnd/src/views/board/QnAEditView.vue
  FrontEnd/src/views/board/QnAView.vue
Labels: duplicate

#26 24 홈 화면 chartjs 추가
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/assets/data/homeChart.js
  FrontEnd/src/assets/styles/main.scss
  FrontEnd/src/assets/styles/test.scss
  FrontEnd/src/components/AppBarChart.vue
  FrontEnd/src/components/AppContent.vue
  FrontEnd/src/components/AppFooter.vue
  FrontEnd/src/components/AppLineChart.vue
  FrontEnd/src/components/AppNav.vue
  FrontEnd/src/views/HomeView.vue
  FrontEnd/src/views/NotFoundView.vue
  FrontEnd/src/views/auth/FindPasswordView.vue
  FrontEnd/src/views/auth/LoginView.vue
  FrontEnd/src/views/auth/SignUpView.vue
  FrontEnd/src/views/board/NoticeCreateView.vue
  FrontEnd/src/views/board/NoticeDetailView.vue
  FrontEnd/src/views/board/NoticeEditView.vue
  FrontEnd/src/views/board/NoticeView.vue
  FrontEnd/src/views/board/QnACreateView.vue
  FrontEnd/src/views/board/QnADetailView.vue
  FrontEnd/src/views/board/QnAEditView.vue
  FrontEnd/src/views/board/QnAView.vue
  FrontEnd/src/views/main/AptInfoView.vue
  FrontEnd/src/views/main/MyPageView.vue
  FrontEnd/vite.config.js
Labels: enhancement

#28 25 axios 라이브러리 등록 및 모듈화 적용
  FrontEnd/src/api/aptInfo.js
  FrontEnd/src/api/board.js
  FrontEnd/src/api/http.js
  FrontEnd/src/components/AppBoardForm.vue
  FrontEnd/src/components/AppContent.vue
  FrontEnd/src/views/auth/FindPasswordView.vue
  FrontEnd/src/views/auth/LoginView.vue
  FrontEnd/src/views/auth/SignUpView.vue
  FrontEnd/src/views/board/NoticeDetailView.vue
  FrontEnd/src/views/board/NoticeView.vue
  FrontEnd/src/views/board/QnADetailView.vue
  FrontEnd/src/views/board/QnAView.vue
  FrontEnd/src/views/main/AptInfoView.vue
Labels: enhancement

#35 34 cors 설정
  backend/src/main/java/com/whereismyhome/board/controller/BoardController.java
  backend/src/main/java/com/whereismyhome/config/AppConfig.java
  backend/src/main/java/com/whereismyhome/config/SecurityConfig.java
Labels: bug

#37 29 aptinfo 사이드 바 content
  FrontEnd/.eslintrc.cjs
  FrontEnd/src/api/aptInfo.js
  FrontEnd/src/api/board.js
  FrontEnd/src/api/http.js
  FrontEnd/src/assets/data/aptData.js
  FrontEnd/src/assets/data/homeChart.js
  FrontEnd/src/components/AppBarChart.vue
  FrontEnd/src/components/AppContent.vue
  FrontEnd/src/components/AppNav.vue
  FrontEnd/src/components/AppSideBar.vue
  FrontEnd/src/views/HomeView.vue
  FrontEnd/src/views/main/AptInfoView.vue
Labels: enhancement

#47 Update feature #45
  FrontEnd/jsconfig.json
  FrontEnd/src/assets/img/apartment00.jpg
  FrontEnd/src/assets/img/apartment05.jpg
  FrontEnd/src/assets/img/notice01.jpg
  FrontEnd/src/assets/img/pageNotFound.jpg
  FrontEnd/src/components/AppNav.vue
  FrontEnd/src/stores/auth.js
  FrontEnd/src/stores/counter.js
  FrontEnd/src/views/auth/FindPasswordView.vue
  FrontEnd/src/views/auth/LoginView.vue
  FrontEnd/src/views/auth/SignUpView.vue
  FrontEnd/src/views/main/AptInfoView.vue
  backend/src/main/java/com/whereismyhome/config/AppConfig.java
  backend/src/main/java/com/whereismyhome/config/SecurityConfig.java
Labels: enhancement

#52 48 공지 글쓰기 api 등록
  FrontEnd/jsconfig.json
  FrontEnd/src/components/AppBoardForm.vue
  FrontEnd/src/components/AppNav.vue
  FrontEnd/src/components/AppPaginationBar.vue
  FrontEnd/src/stores/auth.js
  FrontEnd/src/views/auth/LoginView.vue
  FrontEnd/src/views/board/NoticeCreateView.vue
  FrontEnd/src/views/board/NoticeDetailView.vue
  FrontEnd/src/views/board/NoticeEditView.vue
  FrontEnd/src/views/board/NoticeView.vue
  FrontEnd/src/views/board/QnACreateView.vue
  FrontEnd/src/views/board/QnADetailView.vue
  FrontEnd/src/views/board/QnAEditView.vue
  FrontEnd/src/views/board/QnAView.vue
  backend/src/main/java/com/whereismyhome/config/SecurityConfig.java
Labels: enhancement

#54 게시판, 공지사항 로직 일부 변경
  backend/src/main/java/com/whereismyhome/board/repository/BoardRepository.java
  backend/src/main/java/com/whereismyhome/board/service/BoardService.java
  backend/src/main/java/com/whereismyhome/notice/service/NoticeService.java
Labels: bug

#57 56 라우팅 네비게이션 가드 설정
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.vue
  FrontEnd/src/components/AppAlert.vue
  FrontEnd/src/components/AppContent.vue
  FrontEnd/src/components/AppNav.vue
  FrontEnd/src/composables/alert.js
  FrontEnd/src/main.js
  FrontEnd/src/router/index.js
  FrontEnd/src/stores/alert.js
  FrontEnd/src/stores/auth.js
  FrontEnd/src/views/auth/FindPasswordView.vue
  FrontEnd/src/views/auth/LoginView.vue
  FrontEnd/src/views/auth/SignUpView.vue
  FrontEnd/src/views/board/NoticeCreateView.vue
  FrontEnd/src/views/board/QnACreateView.vue
Labels: enhancement

#59 51 아파트 매매정보 api 작성
  backend/src/main/java/com/whereismyhome/amenities/controller/AmenController.java
  backend/src/main/java/com/whereismyhome/amenities/repository/BusRepository.java
  backend/src/main/java/com/whereismyhome/amenities/repository/CctvRepository.java
  backend/src/main/java/com/whereismyhome/amenities/repository/HospitalRepository.java
  backend/src/main/java/com/whereismyhome/amenities/repository/SchoolRepository.java
  backend/src/main/java/com/whereismyhome/amenities/repository/SubwayRepository.java
  backend/src/main/java/com/whereismyhome/dongcode/entity/DongCode.java
  backend/src/main/java/com/whereismyhome/exception/ExceptionCode.java
  backend/src/main/java/com/whereismyhome/hosedeal/dto/HouseDealResponseDto.java
  backend/src/main/java/com/whereismyhome/hosedeal/entity/HouseDeal.java
  backend/src/main/java/com/whereismyhome/hosedeal/mapper/HouseDealMapper.java
  backend/src/main/java/com/whereismyhome/hosedeal/repository/HouseDealRepository.java
  backend/src/main/java/com/whereismyhome/hosedeal/service/HouseDealService.java
  backend/src/main/java/com/whereismyhome/houseinfo/controller/InfoController.java
  backend/src/main/java/com/whereismyhome/houseinfo/dto/HouseInfoResponseDto.java
  backend/src/main/java/com/whereismyhome/houseinfo/dto/HousePointDto.java
  backend/src/main/java/com/whereismyhome/houseinfo/mapper/HouseInfoMapper.java
  backend/src/main/java/com/whereismyhome/houseinfo/repository/HouseInfoRepository.java
  backend/src/main/java/com/whereismyhome/houseinfo/service/HouseInfoService.java
  backend/src/main/java/com/whereismyhome/main/VueController.java
Labels: enhancement

#61 60 메일 서비스 구현
  backend/build.gradle
  backend/src/main/java/com/whereismyhome/config/SecurityConfig.java
  backend/src/main/java/com/whereismyhome/member/controller/MemberController.java
  backend/src/main/java/com/whereismyhome/member/service/MemberService.java
  backend/src/main/resources/application.yml
Labels: enhancement

#63 58 마이 페이지 UI 생성
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.vue
  FrontEnd/src/assets/styles/test.scss
  FrontEnd/src/components/AppAlert.vue
  FrontEnd/src/components/AppNav.vue
  FrontEnd/src/components/AppSideBar.vue
  FrontEnd/src/main.js
  FrontEnd/src/plugins/kakaoMaps.js
  FrontEnd/src/router/index.js
  FrontEnd/src/stores/sideBar.js
  FrontEnd/src/views/main/AptInfoView.vue
  FrontEnd/src/views/main/MyPageView.vue
  FrontEnd/src/views/main/my/MyBookMarkView.vue
  FrontEnd/src/views/main/my/MyPageView.vue
  FrontEnd/src/views/main/my/MyQnAView.vue
Labels: enhancement

#65 Update feature #62
  FrontEnd/src/components/AppModal.vue
  FrontEnd/src/views/auth/FindPasswordView.vue
  FrontEnd/src/views/auth/LoginView.vue
  FrontEnd/src/views/auth/SignUpView.vue
Labels: duplicate, enhancement

#67 Update feature #66
  FrontEnd/.eslintrc.cjs
  FrontEnd/src/api/amen.js
  FrontEnd/src/api/board.js
  FrontEnd/src/api/bookmark.js
  FrontEnd/src/api/index.js
  FrontEnd/src/api/info.js
  FrontEnd/src/api/member.js
  FrontEnd/src/api/notice.js
  FrontEnd/src/assets/data/sido_gugun.js
  FrontEnd/src/components/AppAlert.vue
  FrontEnd/src/components/AppBarChart.vue
  FrontEnd/src/components/AppContent.vue
  FrontEnd/src/components/AppFooter.vue
  FrontEnd/src/components/AppLineChart.vue
  FrontEnd/src/components/AppModal.vue
  FrontEnd/src/components/AppNav.vue
  FrontEnd/src/components/AppPaginationBar.vue
  FrontEnd/src/components/AppSideBar.vue
  FrontEnd/src/router/index.js
  FrontEnd/src/views/HomeView.vue
  FrontEnd/src/views/NotFoundView.vue
  FrontEnd/src/views/auth/FindPasswordView.vue
  FrontEnd/src/views/auth/LoginView.vue
  FrontEnd/src/views/auth/SignUpView.vue
  FrontEnd/src/views/board/NoticeCreateView.vue
  FrontEnd/src/views/board/NoticeDetailView.vue
  FrontEnd/src/views/board/NoticeEditView.vue
  FrontEnd/src/views/board/NoticeView.vue
  FrontEnd/src/views/board/QnACreateView.vue
  FrontEnd/src/views/board/QnADetailView.vue
  FrontEnd/src/views/board/QnAEditView.vue
  FrontEnd/src/views/board/QnAView.vue
  FrontEnd/src/views/main/AptInfoView.vue
  FrontEnd/src/views/main/my/MyBookMarkInMapView.vue
Labels: duplicate

#70 64 oauth20 sns로그인 구현
  backend/build.gradle
  backend/src/main/java/com/whereismyhome/config/SecurityConfig.java
  backend/src/main/java/com/whereismyhome/member/controller/MemberController.java
  backend/src/main/java/com/whereismyhome/member/mapper/MemberMapper.java
  backend/src/main/java/com/whereismyhome/member/service/MemberService.java
  backend/src/main/java/com/whereismyhome/oauth2/controller/Oauth2Controller.java
  backend/src/main/java/com/whereismyhome/oauth2/dto/TokenDto.java
  backend/src/main/java/com/whereismyhome/oauth2/service/Oauth2Service.java
  backend/src/main/java/com/whereismyhome/role/entity/MemberRole.java
  backend/src/main/resources/application.yml
Labels: enhancement

#71 64 oauth20 sns로그인 구현
  FrontEnd/src/views/auth/LoginView.vue
Labels: enhancement

#73 72 지역별 거래량 조회수 북마크 조회
  backend/src/main/java/com/whereismyhome/amenities/controller/AmenController.java
  backend/src/main/java/com/whereismyhome/amenities/service/AmenService.java
  backend/src/main/java/com/whereismyhome/config/SecurityConfig.java
  backend/src/main/java/com/whereismyhome/houseinfo/controller/InfoController.java
  backend/src/main/java/com/whereismyhome/houseinfo/dto/ChartDataDto.java
  backend/src/main/java/com/whereismyhome/houseinfo/dto/HouseResponseDto.java
  backend/src/main/java/com/whereismyhome/houseinfo/mapper/HouseInfoMapper.java
  backend/src/main/java/com/whereismyhome/houseinfo/repository/HouseInfoRepository.java
  backend/src/main/java/com/whereismyhome/houseinfo/service/HouseInfoService.java
Labels: enhancement

#80 79 마커 관련 api 일괄 수정
  backend/src/main/java/com/whereismyhome/amenities/controller/AmenController.java
  backend/src/main/java/com/whereismyhome/amenities/dto/post/GeoPostDto.java
  backend/src/main/java/com/whereismyhome/amenities/repository/BusRepository.java
  backend/src/main/java/com/whereismyhome/amenities/repository/CctvRepository.java
  backend/src/main/java/com/whereismyhome/amenities/repository/HospitalRepository.java
  backend/src/main/java/com/whereismyhome/amenities/repository/SchoolRepository.java
  backend/src/main/java/com/whereismyhome/amenities/repository/SubwayRepository.java
  backend/src/main/java/com/whereismyhome/amenities/service/AmenService.java
  backend/src/main/java/com/whereismyhome/bookmark/controller/BookMarkController.java
  backend/src/main/java/com/whereismyhome/bookmark/dto/BookMarkDto.java
  backend/src/main/java/com/whereismyhome/bookmark/dto/BookMarkServiceDto.java
  backend/src/main/java/com/whereismyhome/bookmark/dto/BookMarkUpdateDto.java
  backend/src/main/java/com/whereismyhome/bookmark/mapper/BookMarkMapper.java
  backend/src/main/java/com/whereismyhome/bookmark/service/BookMarkService.java
  backend/src/main/java/com/whereismyhome/config/SecurityConfig.java
  backend/src/main/java/com/whereismyhome/houseinfo/controller/InfoController.java
  backend/src/main/java/com/whereismyhome/houseinfo/dto/RankResponseDto.java
  backend/src/main/java/com/whereismyhome/houseinfo/repository/HouseInfoRepository.java
  backend/src/main/java/com/whereismyhome/houseinfo/service/HouseInfoService.java
Labels: enhancement

#82 81 마이페이지 북마크 리스트 정보
  backend/src/main/java/com/whereismyhome/bookmark/controller/BookMarkController.java
  backend/src/main/java/com/whereismyhome/bookmark/dto/BookMarkResponseDto.java
  backend/src/main/java/com/whereismyhome/bookmark/mapper/BookMarkMapper.java
  backend/src/main/java/com/whereismyhome/bookmark/repository/BookMarkRepository.java
  backend/src/main/java/com/whereismyhome/bookmark/service/BookMarkService.java
  backend/src/main/java/com/whereismyhome/houseinfo/repository/HouseInfoRepository.java
Labels: enhancement

#85 76 차트데이터 setting 마커 이벤트 마커 필터링 및 검색
  FrontEnd/.eslintrc.cjs
  FrontEnd/src/api/board.js
  FrontEnd/src/api/bookmark.js
  FrontEnd/src/api/info.js
  FrontEnd/src/api/member.js
  FrontEnd/src/components/chart/AppBarChart.vue
  FrontEnd/src/components/features/AppAlert.vue
  FrontEnd/src/components/features/AppLoading.vue
  FrontEnd/src/components/features/AppPaginationBar.vue
  FrontEnd/src/components/features/AptInfoSideBar.vue
  FrontEnd/src/components/kakao/KaKaoLoadview.vue
  FrontEnd/src/components/kakao/KaKaoMap copy.vue
  FrontEnd/src/components/kakao/KaKaoMap.vue
  FrontEnd/src/components/layouts/AppContent.vue
  FrontEnd/src/components/layouts/AppFooter.vue
  FrontEnd/src/components/layouts/AppNav.vue
  FrontEnd/src/data/sido_gugun.js
  FrontEnd/src/router/index.js
  FrontEnd/src/stores/bookmark.js
  FrontEnd/src/stores/homeChart.js
  FrontEnd/src/stores/kakao.js
  FrontEnd/src/stores/loading.js
  FrontEnd/src/stores/markers.js
  FrontEnd/src/stores/search.js
  FrontEnd/src/stores/sideBar.js
  FrontEnd/src/views/HomeView.vue
  FrontEnd/src/views/NotFoundView.vue
  FrontEnd/src/views/auth/FindPasswordView.vue
  FrontEnd/src/views/auth/LoginView.vue
  FrontEnd/src/views/auth/SignUpView.vue
  FrontEnd/src/views/board/NoticeCreateView.vue
  FrontEnd/src/views/board/NoticeDetailView.vue
  FrontEnd/src/views/board/NoticeEditView.vue
  FrontEnd/src/views/board/NoticeView.vue
  FrontEnd/src/views/board/QnACreateView.vue
  FrontEnd/src/views/board/QnADetailView.vue
  FrontEnd/src/views/board/QnAEditView.vue
  FrontEnd/src/views/board/QnAView.vue
  FrontEnd/src/views/main/AptInfoView.vue
  FrontEnd/src/views/main/my/MyBookMarkInMapView.vue
  FrontEnd/src/views/main/my/MyBookMarkView.vue
  FrontEnd/src/views/main/my/MyPageView.vue
Labels: duplicate

#88 84 전체 아파트 정보 반환
  backend/src/main/java/com/whereismyhome/amenities/controller/AmenController.java
  backend/src/main/java/com/whereismyhome/amenities/service/AmenService.java
  backend/src/main/java/com/whereismyhome/houseinfo/controller/InfoController.java
  backend/src/main/java/com/whereismyhome/houseinfo/dto/HouseResponseDto.java
  backend/src/main/java/com/whereismyhome/houseinfo/entity/HouseInfo.java
  backend/src/main/java/com/whereismyhome/houseinfo/mapper/HouseInfoMapper.java
  backend/src/main/java/com/whereismyhome/houseinfo/repository/HouseInfoRepository.java
  backend/src/main/java/com/whereismyhome/member/service/MemberService.java
Labels: enhancement

#93 Update 회원가입, 비밀번호 변경 인증 #87
  FrontEnd/src/api/member.js
  FrontEnd/src/components/features/AppModal.vue
  FrontEnd/src/views/auth/FindPasswordView.vue
  FrontEnd/src/views/auth/SignUpView.vue
  backend/src/main/java/com/whereismyhome/member/service/MemberService.java
Labels: duplicate

#100 Update #99 중복검사, 북마크
  FrontEnd/src/api/bookmark.js
  FrontEnd/src/api/member.js
  FrontEnd/src/components/features/AptInfoSideBar.vue
  FrontEnd/src/components/kakao/KaKaoMap.vue
  FrontEnd/src/stores/bookmark.js
  FrontEnd/src/views/auth/SignUpView.vue
Labels: duplicate

#107 #103 add: 지역구별 평균 매매가 api 생성
  backend/src/main/java/com/whereismyhome/amenities/mapper/AmenMapper.java
  backend/src/main/java/com/whereismyhome/dongcode/dto/GuGunAvgMountDto.java
  backend/src/main/java/com/whereismyhome/dongcode/mapper/DongCodeMapper.java
  backend/src/main/java/com/whereismyhome/dongcode/repository/DongCodeRepository.java
  backend/src/main/java/com/whereismyhome/dongcode/service/DongCodeService.java
  backend/src/main/java/com/whereismyhome/houseinfo/controller/InfoController.java
Labels: enhancement

#108 106 검색 바 아파트 조회 수정
  FrontEnd/src/api/amen.js
  FrontEnd/src/api/index.js
  FrontEnd/src/api/search.js
  FrontEnd/src/components/features/AptInfoSideBar.vue
  FrontEnd/src/components/kakao/KaKaoMap.vue
  FrontEnd/src/stores/markers.js
  FrontEnd/src/stores/search.js
  FrontEnd/src/views/HomeView.vue
  FrontEnd/src/views/main/AptInfoView.vue
Labels: enhancement

#111 109 사이드바 게시판 수정
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/api/amen.js
  FrontEnd/src/api/info.js
  FrontEnd/src/components/features/AptInfoSideBar.vue
  FrontEnd/src/components/kakao/KaKaoMap.vue
  FrontEnd/src/stores/aptInfo.js
  FrontEnd/src/stores/sideBar.js
  FrontEnd/src/views/auth/LoginView.vue
  FrontEnd/src/views/board/QnADetailView.vue
  FrontEnd/src/views/main/AptInfoView.vue
  FrontEnd/src/views/main/my/MyBookMarkView.vue
  FrontEnd/src/views/main/my/MyPageView.vue
  FrontEnd/src/views/main/my/MyQnAView.vue
Labels: duplicate

#113 112 구별 평균 매매가 오버레이 유저 북마크 지도 생성
  FrontEnd/src/api/info.js
  FrontEnd/src/components/features/AptInfoSideBar.vue
  FrontEnd/src/components/features/MyAptInfoSideBar.vue
  FrontEnd/src/components/kakao/KaKaoMap.vue
  FrontEnd/src/components/kakao/MyKaKaoMap.vue
  FrontEnd/src/plugins/kakaoMaps.js
  FrontEnd/src/stores/bookmark.js
  FrontEnd/src/stores/markers.js
  FrontEnd/src/views/main/AptInfoView.vue
  FrontEnd/src/views/main/my/MyBookMarkInMapView.vue
  FrontEnd/src/views/main/my/MyBookMarkView.vue
  FrontEnd/src/views/main/my/MyQnAView.vue
  FrontEnd/vite.config.js
Labels: enhancement
